program       := { toplevel } ;

toplevel      := struct_decl | fn_decl ;

struct_decl   := "struct" Ident "{" { field_decl } "}" ;
field_decl    := Ident ":" type ";" ;

fn_decl       := "fn" Ident "(" [ params ] ")" "->" type block ;
params        := param { "," param } ;
param         := Ident ":" type ;

block         := "{" { stmt } "}" ;

stmt          := let_stmt
               | assign_stmt
               | expr_stmt
               | return_stmt ;

let_stmt      := "let" [ "mut" ] Ident "=" expr ";" ;

assign_stmt   := lvalue "=" expr ";" ;

lvalue        := Ident
               | expr "." Ident ;   // MVP: field assignment target

return_stmt   := "return" [ expr ] ";" ;
expr_stmt     := expr ";" ;

expr          := equality ;
equality      := add { ("==" | "!=") add } ;
add           := unary { ("+" | "-") unary } ;
unary         := ("&" | "&mut" | "-") unary | postfix ;
postfix       := primary { "." Ident } ;

primary       := IntLit
               | StringLit
               | "true" | "false"
               | Ident
               | struct_lit
               | call
               | "(" expr ")" ;

call          := Ident "(" [ args ] ")" ;
args          := expr { "," expr } ;

struct_lit    := Ident "{" [ field_inits ] "}" ;
field_inits   := field_init { "," field_init } ;
field_init    := Ident ":" expr ;

type          := "Int" | "Bool" | "String" | "Void"
               | Ident                      // struct type name
               | "&" type
               | "mut" "&" type ;           // mut &T

unary         := ("ref" | "refmut" | "-") unary | postfix ;

type          := ... | "ref" type | "refmut" type ;